### ISSUE TITLE
want to add cpp solution to a leetcode medium problem

### ISSUE THREAD

**Issue by raj-hero** [PraSarOG/Hacktoberfest-22#257]
I want to add cpp solution to leetcode's 4 sum medium problem. Also, what points should I take care of for the PR to be hacktober-accepted?

**Comment by PraSarOG** [comment]
Don't worry, just add your code to be accepted...

**Comment by cheemsjs** [comment]
Contribute here : https://github.com/cheemsjs/hacktoberfest-22
